#!/bin/bash
#$ -wd /data/scratch/btx654/
#$ -o /data/scratch/btx654/
#$ -j y
#$ -pe smp 30
#$ -l h_vmem=5G
#$ -l h_rt=240:00:0
#$ -l highmem

species=$1
gffread_proteins="$species"_proteins.fa #generated by gffread_universal_8.1_v1.sh
gffread_proteins_path=/data/scratch/btx654/btx604-scratch/$species/New_annotation_Dec2020/step8/$gffread_proteins
panther_output="$species"_Panther

echo "Working on "$species

cd /data/scratch/btx654/btx604-scratch/$species/New_annotation_Dec2020/

mkdir -p step9
cd step9

cp $gffread_proteins_path ./

module load perl
module load hmmer/

export PERL5LIB=/data/SBCS-MartinDuranLab/03-Giacomo/src/hmmscoring/lib/

perl /data/SBCS-MartinDuranLab/03-Giacomo/src/hmmscoring/pantherScore2.2.pl -l /data/SBCS-MartinDuranLab/03-Giacomo/src/hmmscoring/PANTHER15.0/ -D B -n -o $panther_output -i $gffread_proteins -c 30 -V -s

mkdir /data/SBCS-MartinDuranLab/03-Giacomo/data/$species/annotation/New_annotation_Dec2020/step9
cp "$species"_Panthe* /data/SBCS-MartinDuranLab/03-Giacomo/data/$species/annotation/New_annotation_Dec2020/step9
